### ISSUE TITLE
UTF-8 Problem

### ISSUE THREAD

**Issue by melih** [yuxel/SqlDumb#1]
After importing backup file, I see question marks instead of Turkish characters.

**Comment by yuxel** [comment]
can you see this characters properly on dumped file?

if so, it should be something related with your database's character set and collation settings

**Comment by melih** [comment]
There are question marks in dumped file also. For the full solution the code below should be added after `mysql_select_db`.

`mysql_query("SET NAMES 'utf8'");`

Thank you again.
